"""add phone number

Revision ID: 2d49e6a1fddc
Revises: c47ecbf163d4
Create Date: 2026-03-27 01:34:50.180306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d49e6a1fddc'
down_revision = 'c47ecbf163d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
